# Generated by Django 4.1.5 on 2023-02-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('birthdate', models.DateField(blank=True)),
                ('gender', models.CharField(choices=[('erkak', 'Erkak'), ('ayol', 'Ayol')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.DateField(blank=True)),
                ('imdb', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Komik', 'Komediya'), ('drama', 'Drama'), ('detektiv', 'Detektiv'), ('jangari', 'Jangari')], max_length=20)),
                ('actor', models.ManyToManyField(to='movie.actor')),
            ],
        ),
    ]
