# Generated by Django 4.1.5 on 2023-02-22 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_alter_comment_send_time_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2023, 2, 22, 16, 39, 58, 614818, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.FloatField(),
        ),
    ]
