# Generated by Django 4.1.5 on 2023-02-23 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_alter_comment_send_time_alter_movie_imdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='send_time',
            field=models.DateField(default=datetime.datetime(2023, 2, 23, 7, 54, 25, 143231)),
        ),
    ]
